"use client";
import {useEffect,useState} from "react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from "@/components/ui/table";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import { Activity, ArrowUpRight, ShieldCheck, RefreshCw } from "lucide-react";
import {risks,type Snapshot} from "@/lib/health";
import Preferences from "./preferences";
import {Roadmap} from "./report-views";
import SteerCo from './steerco';
import {defaultPreferences,type Preferences as Prefs} from "@/lib/preferences";
import {DeliveryBrief,ManagerDecisions} from './delivery-brief';
import DeliveryArchitecture from './delivery-architecture';
const colors:Record<string,string>={"Done":"#16846c","In Progress":"#315edf","Testing":"#bd840a","To Do":"#9daec5","Idea":"#a7b3c5","Under Review":"#6479a4"};
const date=(s:string)=>new Date(s).toLocaleString("en-IN",{timeZone:"Asia/Kolkata",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"});
const issueLink=(k:string)=>"https://shru2128.atlassian.net/browse/"+encodeURIComponent(k);
export default function Dashboard({initial}: {initial: any}) {
 const [prefs,setPrefs]=useState<Prefs>(defaultPreferences);
 useEffect(()=>{fetch("/api/preferences").then(r=>r.json()).then((d:any)=>{if(d.preferences)setPrefs(d.preferences);}).catch(()=>{});},[]);
 const [data,setData]=useState<Snapshot>(initial),[history,setHistory]=useState<any[]>([]),[period,setPeriod]=useState<'daily'|'weekly'>('daily'),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[filter,setFilter]=useState("all");
 const comparison=period==='daily'?data.delivery?.daily:data.delivery?.weekly;
 async function load(){const r=await fetch("/api/dashboard",{cache:"no-store"}),d:any=await r.json();if(!r.ok)throw new Error(d.error);setData(d.snapshot);setHistory(d.history);}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:"read_delivery_snapshot",description:"Read the same dated portfolio snapshot currently displayed. Does not refresh Jira or expose integration settings.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("Expected an empty object");return {fetchedAt:data.fetchedAt,projects:data.projects,issues:data.issues.map(i=>({key:i.key,status:i.status,assignee:i.assignee,updated:i.updated})),assessment:data.assessment};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[data]);
 async function refresh(){setBusy(true);setMessage("");try{const r=await fetch("/api/refresh",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}),d:any=await r.json();if(!r.ok)throw new Error(d.error);setData(d.snapshot);await load();setMessage("Fresh Jira snapshot saved. Review any provider warnings below.");}catch(e){setMessage(e instanceof Error?e.message:"Refresh failed.");}finally{setBusy(false);}}
 const selected=data.issues.filter(i=>filter==="all"||i.project===filter),riskItems=risks(data).filter(i=>filter==="all"||i.project===filter);
 const dependencyItems=selected.filter(i=>i.category!=="Done"&&(/depend|blocked|unconfirmed|conflict/i.test(i.description)||i.links.length));
 return <div className="shell"><header><a className="brand" href="/"><span className="brandmark"><Activity size={24}/></span>Delivery Feedback</a><a className="quiet-link" href="/settings"><ShieldCheck size={18}/> Secure integrations</a></header><main>
 <div className="page-title"><div><p className="eyebrow">PROGRAM OPERATIONS / PORTFOLIO</p><h1>Delivery, in focus.</h1><p className="muted">All projects. Clear ownership. Evidence before confidence.</p></div><Button disabled={busy} onClick={refresh}><RefreshCw size={16}/>{busy?"Retrieving Jira…":"Refresh Jira"}</Button></div>
 <div className="freshness"><ShieldCheck size={15}/> {data.source} · {date(data.fetchedAt)} IST <span>{prefs.enabled?`${prefs.cadence} · ${prefs.time} IST · scheduled preference`:"Scheduled reports paused"}</span></div>
 {Date.now()-new Date(data.fetchedAt).getTime()>8*86400000&&<div className="stale">This snapshot is more than eight days old. Refresh before making a delivery commitment.</div>}
 <p className="notice" role="status">{message}</p>
 <Tabs defaultValue="steerco"><TabsList variant="line" className="main-tabs"><TabsTrigger value="steerco">SteerCo</TabsTrigger><TabsTrigger value="business">Business Delivery</TabsTrigger><TabsTrigger value="roadmap">Product Roadmap</TabsTrigger><TabsTrigger value="preferences">Preferences</TabsTrigger></TabsList>
 <TabsContent value="steerco"><SteerCo data={data} prefs={prefs}/></TabsContent>
 <TabsContent value="roadmap"><Roadmap data={data}/></TabsContent>
 <TabsContent value="preferences"><Preferences onSaved={setPrefs}/><DeliveryArchitecture/></TabsContent>
 <TabsContent value="business"><section className="headline"><span className="tag">PM ASSESSMENT · AS OF SNAPSHOT</span><h2>{data.delivery?.headline??data.assessment}</h2><p>{data.sprintNote} {data.sprints.length===0?"No active sprint metadata is recorded; do not interpret this as sprint completion.":data.sprints.length+" active sprints retrieved."}</p></section><ManagerDecisions report={data.delivery}/>
 <div className="metrics">{[["Total records",data.issues.length],["Done",data.issues.filter(i=>i.category==="Done").length],["Active status labels",data.issues.filter(i=>["In Progress","Testing"].includes(i.status)).length],["Needs attention",risks(data).length]].map(([label,value])=><section className="metric" key={label}><p>{label}</p><strong>{value}</strong><small>Current Jira snapshot</small></section>)}</div>
 <Tabs defaultValue="portfolio"><div className="split"><TabsList variant="line"><TabsTrigger value="portfolio">Portfolio</TabsTrigger><TabsTrigger value="risks">Risks & dependencies</TabsTrigger><TabsTrigger value="history">Daily / weekly changes</TabsTrigger></TabsList><Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="Filter project"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All projects</SelectItem>{data.projects.map(p=><SelectItem key={p.key} value={p.key}>{p.name}</SelectItem>)}</SelectContent></Select></div>
 <TabsContent value="portfolio"><div className="projects">{data.projects.filter(p=>filter==="all"||filter===p.key).map(p=>{const issues=data.issues.filter(i=>i.project===p.key);const counts=issues.reduce<Record<string,number>>((a,i)=>({...a,[i.status]:(a[i.status]??0)+1}),{});return <article className="project" key={p.key}><div className="row"><span className="project-key">{p.key}</span><a aria-label={"Open "+p.name+" in Jira"} href={"https://shru2128.atlassian.net/issues/?jql="+encodeURIComponent('project = "'+p.key+'"')} target="_blank" rel="noreferrer"><ArrowUpRight size={18}/></a></div><h2>{p.name}</h2><p className="muted">{issues.length} issues · {issues.filter(i=>i.category!=="Done"&&!i.assignee).length} unassigned open</p><div className="bar" aria-hidden="true">{Object.entries(counts).map(([s,n])=><span key={s} style={{background:colors[s]??"#64748b",width:n/issues.length*100+"%"}}/>)}</div><div className="status-list">{Object.entries(counts).map(([s,n])=><div className="row" key={s}><span><i className="status-dot" style={{background:colors[s]??"#64748b"}}/>{s}</span><strong>{n}</strong></div>)}</div></article>})}</div><p className="footnote">Counts include epics/features and children—not independent deliverables or percent completion. Status labels and counts identify every chart segment.</p>
 <div className="issue-table"><Table><TableHeader><TableRow><TableHead>Issue</TableHead><TableHead>Delivery item</TableHead><TableHead>Status</TableHead><TableHead>Assignee</TableHead><TableHead>Updated · IST</TableHead></TableRow></TableHeader><TableBody>{selected.map(i=><TableRow key={i.key}><TableCell><a className="issue-key" href={issueLink(i.key)} target="_blank" rel="noreferrer">{i.key}</a></TableCell><TableCell>{i.summary}<div className="footnote">{i.type} · {i.priority??"No priority"}</div></TableCell><TableCell>{i.status}</TableCell><TableCell>{i.assignee??"Unassigned"}</TableCell><TableCell>{date(i.updated)}</TableCell></TableRow>)}</TableBody></Table></div></TabsContent>
 <TabsContent value="risks"><div className="risk-grid"><section className="panel"><h2>Attention queue <span className="badge">{riskItems.length}</span></h2><p className="muted">Rule-based signals, not proof that delivery is blocked. Staleness is measured at the snapshot date.</p>{riskItems.length===0&&<p className="empty-note">No issues match the current risk rules.</p>}{riskItems.map(i=><article className="risk-row" key={i.key}><a className="issue-key" href={issueLink(i.key)} target="_blank" rel="noreferrer">{i.key} ↗</a><p>{i.summary}</p><div className="chips">{i.reasons.map(r=><span className="chip" key={r}>{r}</span>)}</div><small>{i.status} · {i.assignee??"Unassigned"} · updated {date(i.updated)} IST</small></article>)}</section><section className="panel"><h2>Dependency evidence</h2><p className="muted">Descriptions mentioning dependencies, uncertainty or decisions. Text mentions are not verified blocking links.</p>{dependencyItems.map(i=><article className="risk-row" key={i.key}><a className="issue-key" href={issueLink(i.key)} target="_blank" rel="noreferrer">{i.key} ↗</a><p>{i.summary}</p><small>{i.status} · {i.assignee??"Unassigned"}</small><details><summary>Read Jira evidence</summary><div className="description">{i.description||"No description."}</div>{i.links.length>0&&<p>{i.links.map((l:any)=>[l.type?.inward,l.inwardIssue?.key,l.type?.outward,l.outwardIssue?.key].filter(Boolean).join(" ")).join("; ")}</p>}</details></article>)}</section></div></TabsContent>
 <TabsContent value="history"><section className="panel"><Select value={period} onValueChange={v=>setPeriod(v as 'daily'|'weekly')}><SelectTrigger aria-label="Comparison period"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="daily">Previous IST day</SelectItem><SelectItem value="weekly">Seven IST days earlier</SelectItem></SelectContent></Select><h2>{comparison?"What changed since "+date(comparison.since)+" IST":"Comparison baseline unavailable"}</h2>{comparison?<><p className="muted">Uses the latest same-scope snapshot on the exact {period==='daily'?'previous IST calendar day':'IST calendar day seven days earlier'}. “No longer visible” may indicate permission/scope changes—not completion.</p><p>{comparison.added.length} newly visible · {comparison.changes.length} status/owner changes · {comparison.noLongerVisible.length} no longer visible</p>{comparison.changes.map(c=><div className="history-row" key={c.key}><a className="issue-key" href={issueLink(c.key)}>{c.key}</a><span>{c.from} → {c.to} · {c.previousAssignee??"Unassigned"} → {c.assignee??"Unassigned"}</span></div>)}<h3>Risks recurring across snapshots</h3><p>{comparison.recurring.length?comparison.recurring.join(", "):"None identified."}</p><p className="footnote">Recurring signals are not evidence of multi-sprint blockage. Sprint history is required for that claim.</p></>:<p className="empty-note">No same-scope snapshot was found on the {period==='daily'?'previous IST day':'IST day seven days earlier'}. An older date is not silently substituted.</p>}</section><section className="panel"><h2>Snapshot ledger</h2>{history.map(h=><div className="history-row" key={h.id}><strong>{date(h.fetchedAt)} IST</strong><span>{h.issues} issues · {h.source}</span></div>)}</section><section className="panel"><h2>Historical memory</h2><p className="muted">Retrieved context is not a current-status source.</p><p>{data.memory?.mem0??"Mem0: not run for this snapshot"} · {data.memory?.pinecone??"Pinecone: not run for this snapshot"}</p>{[...(data.memory?.mem0History??[]),...(data.memory?.pineconeHistory??[])].map((m:any,n:number)=><details key={n}><summary>Historical evidence {n+1} · {m.created??"date unavailable"}</summary><p className="description">{m.text}</p></details>)}</section></TabsContent></Tabs>
 </TabsContent></Tabs>
 {data.warnings.length>0&&<details className="sc-source-details"><summary>Source and integration details</summary>{data.warnings.map((w,n)=><p key={n} className="muted">{w}</p>)}</details>}
 </main><footer>Current facts: Jira. Historical context: dated snapshots, Mem0 and Pinecone when enabled. Scheduled updates require the Codex task host to be available.</footer></div>;
}
