'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {risks,type Snapshot} from '@/lib/health';
import type {Preferences} from '@/lib/preferences';
const link=(k:string)=>'https://shru2128.atlassian.net/browse/'+encodeURIComponent(k);
const stages:Record<string,{phase:string;gate:string;keys:string[];months:string[]}>={
 AUT:{phase:'Discovery / Define',gate:'Approve scope, architecture and discovery exit criteria.',keys:['AUT-11','AUT-12','AUT-13'],months:['Discovery & define','Design review','Vertical-slice build','Validate','Conditional pilot','Release review']},
 KAN:{phase:'Validate · launch gate open',gate:'Agree text-first launch scope and acceptance evidence. Voice remains deferred.',keys:['KAN-11','KAN-14','KAN-18','KAN-19'],months:['Text-first validation','Conditional pilot','Launch decision','Operate / measure','Improve','Review next scope']},
 SMB:{phase:'Validate · readiness gate open',gate:'Confirm owners, resolve memory evidence conflicts and complete regression evidence.',keys:['SMB-16','SMB-19','SMB-20','SMB-21'],months:['Post-submission hardening','Conditional pilot','Release decision','Operate / measure','Improve','Review next scope']}
};
export function SteerCo({data,prefs}:{data:Snapshot;prefs:Preferences}){
 const done=data.issues.filter(i=>i.category==='Done').length;
 return <><section className="executive-heading"><span className="tag">STEERING COMMITTEE · EVIDENCE BRIEF</span><div className="row"><h2>Progress needs a decision, not a percentage.</h2><a className="download-link" href="/api/presentation">Download PowerPoint ↗</a></div><p>{data.assessment}</p><p className="footnote">PowerPoint is the latest generated edition; its cover carries its own source timestamp. Jira refresh and slide generation are separate steps.</p></section><div className="metrics">{[['Projects',data.projects.length],['Done records',done],['Open records',data.issues.length-done],['Need attention',risks(data).length]].map(([label,n])=><section className="metric" key={label}><p>{label}</p><strong>{n}</strong><small>As of {new Date(data.fetchedAt).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'})}</small></section>)}</div><div className="projects">{data.projects.map(p=>{const s=data.delivery?.projects.find(project=>project.key===p.key)?.pdlc??data.projectAssessments?.[p.key]??stages[p.key],items=data.issues.filter(i=>i.project===p.key);return <article className="project" key={p.key}><span className="tag">{prefs.agents[p.key as keyof Preferences['agents']]??p.key} · {p.key}</span><h2>{p.name}</h2><p className="phase-label">{s?.phase??'Phase not assessed'}</p><p>{items.filter(i=>i.category==='Done').length} Done / {items.length} tracked records</p><h3>Decision / next gate</h3><p>{s?.gate??'Review source evidence before assessing.'}</p>{s?.keys.filter(k=>items.some(i=>i.key===k)).map(k=>{const i=items.find(i=>i.key===k)!;return <div className="exec-evidence" key={k}><a className="issue-key" href={link(k)} target="_blank" rel="noreferrer">{k}</a><span>{i.status} · {i.assignee??'Unassigned'}</span></div>;})}</article>;})}</div><section className="panel"><h3>Confidence boundaries</h3><p>Unless a refreshed PDLC assessment is supplied, phases and gates retain the 11 September baseline. PDLC phases and gate readiness are delivery-manager assessments, not Jira workflow fields. Issue counts include parent and child records; they are not a release-completion percentage. Budget, capacity and product-outcome baselines are not available.</p></section></>;
}
export function Roadmap({data}:{data:Snapshot}){
 const [months,setMonths]=useState(6);
 return <><section className="panel"><div className="row"><div><span className="tag">PDLC · PROPOSED PLANNING SCENARIO</span><h2>October 2026 → March 2027</h2></div><Button variant="outline" onClick={()=>setMonths(months===6?3:6)}>Show {months===6?3:6} months</Button></div><p>Months 1–3 are sample planning windows; months 4–6 are directional. No dates below are approved commitments or written back to Jira. Engineering capacity and gate approvals must be confirmed.</p><p className="stale">Existing commitments are separate: review SMB-19 for the recorded 12 September submission requirement and its unconfirmed exact time. This scenario does not move that deadline.</p></section><div className="issue-table roadmap"><Table><TableHeader><TableRow><TableHead>Project / assessed PDLC</TableHead>{['Oct 2026','Nov','Dec','Jan 2027','Feb','Mar'].slice(0,months).map(m=><TableHead key={m}>{m}</TableHead>)}</TableRow></TableHeader><TableBody>{data.projects.map(p=><TableRow key={p.key}><TableCell><strong>{p.name}</strong><p className="footnote">{data.delivery?.projects.find(project=>project.key===p.key)?.pdlc.phase??stages[p.key]?.phase??'Unassessed'}</p></TableCell>{stages[p.key]?.months.slice(0,months).map((m,i)=><TableCell key={m}><span className={'timeline-cell phase-'+i}>{m}</span></TableCell>)}</TableRow>)}</TableBody></Table></div><section className="panel"><h2>Gates before dates</h2><div className="pdlc-flow">{['Discover / Define','Design','Build','Validate','Launch','Operate'].map((s,i)=><div key={s}><small>GATE {i+1}</small><strong>{s}</strong><p>{['Problem and scope approved','Design and risks reviewed','Acceptance scope implemented','Dated test evidence accepted','Owner go / no-go','Outcomes and incidents reviewed'][i]}</p></div>)}</div><p>Cross-functional dependency ownership and need-by dates remain unconfirmed. Missing evidence never counts as a passed gate.</p></section><section className="panel"><h2>Jira roadmap source</h2><p>Open the existing project records to review approved dates. Native Jira timelines require real epic dates and a supported timeline view; the sample above is not a published Jira roadmap.</p>{data.projects.map(p=><p key={p.key}><a className="issue-key" target="_blank" rel="noreferrer" href={'https://shru2128.atlassian.net/issues/?jql='+encodeURIComponent('project = '+p.key+' ORDER BY key ASC')}>{p.name} · Jira records ↗</a></p>)}<p className="footnote">No invented milestone issues, assignments, dates or cross-project blocking links.</p></section></>;
}
