'use client';
import {useRef,useState} from 'react';
import {ArrowDownToLine,ChevronLeft,ChevronRight,Expand,Minimize,Presentation,TriangleAlert,Users,Wallet,GitBranch,CheckCircle2,Clock3,LoaderCircle,ArrowUpRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {steercoModel,type BoardRisk} from '@/lib/steerco';
import type {Snapshot,Issue} from '@/lib/health';
import type {Preferences} from '@/lib/preferences';
const source=(k:string)=>'https://shru2128.atlassian.net/browse/'+encodeURIComponent(k);
const date=(d:string)=>new Date(d).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
function Evidence({items}:{items:Issue[]}){return <details className="sc-evidence"><summary>{items.length?`View ${items.length} Jira evidence ${items.length===1?'item':'items'}`:'Reporting input not available'}</summary>{items.length?items.map(i=><div key={i.key}><a href={source(i.key)} target="_blank" rel="noreferrer">{i.key}<ArrowUpRight size={13}/></a><span>{i.summary}</span><small>{i.status} / {i.assignee??'Unassigned'} / updated {date(i.updated)} IST</small></div>):<p>This input is absent from the connected reporting dataset. Confirm it with the proposed role before the decision.</p>}</details>;}
function Ring({done,active,remaining}:{done:number;active:number;remaining:number}){const total=done+active+remaining,c=2*Math.PI*48;return <div className="sc-ring"><svg viewBox="0 0 120 120" role="img" aria-label={`${done} Done, ${active} active, ${remaining} other records`}><circle cx="60" cy="60" r="48" fill="none" stroke="#e1e6ef" strokeWidth="10"/>{total>0&&[[done,'#14a080',0],[active,'#526af2',done]].map(([n,color,offset],i)=><circle key={i} cx="60" cy="60" r="48" fill="none" stroke={String(color)} strokeWidth="10" strokeDasharray={`${Number(n)/total*c} ${c}`} strokeDashoffset={-Number(offset)/total*c} transform="rotate(-90 60 60)"/>)}<text x="60" y="59" textAnchor="middle" className="ring-number">{done}</text><text x="60" y="79" textAnchor="middle" className="ring-label">Done</text></svg></div>;}
function RiskCard({risk}:{risk:BoardRisk}){return <article className={`sc-risk ${risk.level==='Escalate'?'is-red':'is-amber'}`}><div className="sc-risk-top"><span className="sc-severity"><TriangleAlert size={15}/>{risk.level}</span><span>{risk.kind}</span></div><h3>{risk.title}</h3><p>{risk.impact}</p><div className="sc-action"><strong>Next action</strong><p>{risk.action}</p></div><small>Owner: {risk.owner}<br/>Decision gate: {risk.decisionBy}</small><Evidence items={risk.evidence}/></article>;}
export default function SteerCo({data,prefs}:{data:Snapshot;prefs:Preferences}){
 const model=steercoModel(data,prefs),[slide,setSlide]=useState(0),[expanded,setExpanded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),root=useRef<HTMLDivElement>(null);
 async function download(){setBusy(true);setMessage('');try{const r=await fetch('/api/presentation?snapshotId='+encodeURIComponent(data.id),{cache:'no-store'});if(!r.ok){const d:any=await r.json();throw Error(d.error??'PowerPoint is unavailable.');}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='SteerCo-'+data.fetchedAt.slice(0,10)+'.pptx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('PowerPoint exported.');}catch(e){setMessage(e instanceof Error?e.message:'Export failed.');}finally{setBusy(false);}}
 const deck=<div ref={root} className={`sc-workspace ${expanded?'sc-expanded':''}`}><div className="sc-toolbar"><div className="sc-title"><span className="sc-deck-icon"><Presentation size={24}/></span><div><h2>Steering committee</h2><p>{date(data.fetchedAt)} IST</p></div></div><div className="sc-tools"><Button variant="outline" onClick={()=>setExpanded(!expanded)} aria-label={expanded?'Exit presentation view':'Open presentation view'}>{expanded?<Minimize size={17}/>:<Expand size={17}/>}<span>{expanded?'Exit':'Present'}</span></Button><Button className="sc-export" disabled={busy} onClick={download}>{busy?<LoaderCircle className="sc-spin" size={18}/>:<ArrowDownToLine size={18}/>}<span>{busy?'Preparing…':'Export PowerPoint'}</span><span className="sc-filetype">PPTX</span></Button></div></div>
 <div className="sc-layout"><nav className="sc-agenda" aria-label="SteerCo agenda"><p>MEETING AGENDA</p>{model.agenda.map((title,i)=><button key={title} aria-current={slide===i?'step':undefined} className={slide===i?'selected':''} onClick={()=>setSlide(i)}><span>{String(i+1).padStart(2,'0')}</span>{title}{i===1&&<b>{model.risks.length}</b>}</button>)}<div className="sc-agenda-bottom"><Clock3 size={16}/><span>Snapshot-based review<br/>Actions require owner approval</span></div></nav>
 <section className="sc-canvas" aria-label={model.agenda[slide]}><div className="sc-slide-heading"><div><p className="sc-kicker">{String(slide+1).padStart(2,'0')} / STEERCO BRIEFING</p><h2>{['Three projects. Decisions ahead.','Risks requiring intervention','Inputs for funding and board approval','Decisions awaiting an owner','Choices and their consequences'][slide]}</h2></div><span className="sc-slide-no">{slide+1} / 5</span></div>
 {slide===0&&<><div className="sc-scoreboard">{[[TriangleAlert,model.highDefects,'High-priority open defects','red'],[Users,model.unassigned,'Unassigned open records','amber'],[GitBranch,model.risks.length,'Delivery risk themes','amber'],[Wallet,model.planning.length,'Budget / board input gaps','blue']].map(([Icon,n,label,tone]:any)=><button key={label} className={`sc-score ${tone}`} onClick={()=>setSlide(tone==='blue'?2:1)}><Icon size={20}/><strong>{n}</strong><span>{label}</span></button>)}</div><div className="sc-agents">{model.projects.map(p=><article key={p.key} className="sc-agent"><div className="sc-agent-heading"><span className={'sc-avatar agent-'+p.key}>{p.agent.slice(0,1)}</span><div><h3>{p.agent}</h3><p>{p.name}</p></div><span className={'sc-health '+(p.level==='Escalate'?'red':p.level==='No flagged risk'?'green':'amber')}>{p.level==='Escalate'?<TriangleAlert size={14}/>:p.level==='No flagged risk'?<CheckCircle2 size={14}/>:<Clock3 size={14}/>} {p.level}</span></div><div className="sc-agent-chart"><Ring done={p.done} active={p.active} remaining={p.remaining}/><div className="sc-status-counts"><p><i className="done"/>Done <strong>{p.done}</strong></p><p><i className="active"/>Active <strong>{p.active}</strong></p><p><i className="other"/>Other statuses <strong>{p.remaining}</strong></p></div></div><div className="sc-agent-stats"><div><strong>{p.high}</strong><span>High defects</span></div><div><strong>{p.unassigned}</strong><span>Unassigned</span></div><div><strong>{p.total}</strong><span>Records</span></div></div><div className="sc-next-gate"><span>NEXT DISCUSSION</span><p>{p.gate?.summary??(p.high?'Verify open defects before release.':'Confirm delivery scope and accountable owners.')}</p></div><div className="sc-agent-source"><Clock3 size={14}/>Agent update: {p.agentState==='Unavailable'?'not collected':p.agentState.toLowerCase()}</div><Evidence items={p.evidence}/></article>)}</div><div className="sc-bottom-line"><TriangleAlert size={20}/><p><strong>Board attention:</strong> {model.highDefects} high-priority defects remain open. Funding and delivery commitments also need the missing budget and capacity inputs.</p><button onClick={()=>setSlide(1)}>Review risks <ChevronRight size={17}/></button></div><p className="sc-note">Charts show Jira records, including parents and children. They do not measure release completion.</p></>}
 {slide===1&&<><p className="sc-intro">Escalations include an impact, an accountable owner or ownership gap, and a proposed response.</p><div className="sc-risk-grid">{model.risks.map(r=><RiskCard key={r.id} risk={r}/>)}{!model.risks.length&&<p>No delivery risk rule matched. Review the planning gaps before making commitments.</p>}</div></>}
 {slide===2&&<><p className="sc-intro">These are risks to making an informed commitment. They describe missing reporting inputs, not proven budget overruns.</p><div className="sc-planning">{model.planning.map((r,i)=><div key={r.id}><div className="sc-gap-icon">{i===0?<Wallet/>:i===1?<Users/>:<Presentation/>}<span>INPUT NEEDED</span></div><RiskCard risk={r}/></div>)}</div></>}
 {slide===3&&<><p className="sc-intro">Pending recommendations for SteerCo approval. No proposed owner, date or choice has been written to Jira.</p><div className="sc-decision-list">{model.decisions.map((d,i)=><article key={d.id}><span className="sc-decision-number">{String(i+1).padStart(2,'0')}</span><div><h3>{d.action}</h3><p>{d.title}</p><small>Accountability: {d.owner}<br/>Needed: {d.decisionBy}</small><Evidence items={d.evidence}/></div><span className="sc-pending">Pending</span></article>)}</div></>}
 {slide===4&&<><p className="sc-intro">Options for discussion. Cost and schedule impacts need quantification before approval.</p><div className="sc-trades">{model.trades.map(t=><article key={t.id}><div className="sc-trade-title"><h3>{t.title}</h3><p>{t.question}</p></div><div className="sc-options">{[t.a,t.b].map((o,i)=><div key={o.title}><span>OPTION {i===0?'A':'B'}</span><h4>{o.title}</h4><p className="sc-gain"><CheckCircle2 size={15}/>{o.gain}</p><p className="sc-cost"><TriangleAlert size={15}/>{o.cost}</p></div>)}</div><div className="sc-recommendation"><strong>Proposed approach</strong><p>{t.recommendation}</p></div><Evidence items={t.evidence}/></article>)}</div></>}
 </section></div><div className="sc-footer"><p role="status">{message||'Jira facts with clearly labelled PM assessments'}</p><div><Button variant="outline" disabled={slide===0} onClick={()=>setSlide(slide-1)} aria-label="Previous agenda item"><ChevronLeft size={17}/></Button><span>{model.agenda[slide]}</span><Button variant="outline" disabled={slide===4} onClick={()=>setSlide(slide+1)} aria-label="Next agenda item"><ChevronRight size={17}/></Button></div></div></div>;
 return expanded?<Dialog open onOpenChange={setExpanded}><DialogContent className="sc-present-dialog" showCloseButton={false}><DialogTitle className="sr-only">Steering committee presentation</DialogTitle><DialogDescription className="sr-only">Use the agenda or previous and next buttons to move through the briefing. Escape closes presentation mode.</DialogDescription>{deck}</DialogContent></Dialog>:deck;
}
