import {z} from 'zod';
import {agentTasks} from './preferences.ts';
export const agentEvidenceSchema=z.array(z.object({project:z.enum(['AUT','KAN','SMB']),taskId:z.string().max(100),checkedAt:z.string().datetime(),summary:z.string().max(3000),sourceUpdatedAt:z.string().datetime({offset:true}).nullable(),claims:z.array(z.object({key:z.string().regex(/^(AUT|KAN|SMB)-\d+$/),status:z.string().max(100).optional(),completed:z.boolean().optional()}).strict()).max(100).optional()}).strict()).max(3).superRefine((rows,c)=>{
 if(new Set(rows.map(e=>e.project)).size!==rows.length)c.addIssue({code:'custom',message:'Duplicate agent project'});
 for(const e of rows){
  if(e.taskId!==agentTasks[e.project])c.addIssue({code:'custom',message:'Agent task does not match project'});
  if(Date.parse(e.checkedAt)>Date.now()+60000||e.sourceUpdatedAt&&Date.parse(e.sourceUpdatedAt)>Date.parse(e.checkedAt))c.addIssue({code:'custom',message:'Invalid evidence timestamps'});
  if(e.claims?.some(i=>!i.key.startsWith(e.project+'-')))c.addIssue({code:'custom',message:'Claim project mismatch'});
 }
});
const issue=z.object({key:z.string().regex(/^(AUT|KAN|SMB)-\d+$/),project:z.enum(['AUT','KAN','SMB']),summary:z.string().max(2000),status:z.string().max(100),category:z.string().max(100),assignee:z.string().max(300).nullable(),updated:z.string().max(60),created:z.string().max(60),type:z.string().max(100),priority:z.string().max(100).optional(),description:z.string().max(50000),due:z.string().max(20).nullable(),links:z.array(z.unknown()).max(100),flagged:z.boolean().optional()}).strict();
export const snapshotSchema=z.object({id:z.string().max(120),fetchedAt:z.string().datetime(),source:z.string().max(200),projects:z.array(z.object({key:z.enum(['AUT','KAN','SMB']),name:z.string().max(200)})).length(3),issues:z.array(issue).max(2000),sprints:z.array(z.unknown()).max(100),sprintNote:z.string().max(2000),warnings:z.array(z.string().max(2000)).max(30),assessment:z.string().max(3000),projectAssessments:z.record(z.enum(['AUT','KAN','SMB']),z.object({phase:z.string().max(150),gate:z.string().max(1000),keys:z.array(z.string().regex(/^(AUT|KAN|SMB)-\d+$/)).max(10)})).optional(),agentEvidence:z.array(z.object({project:z.enum(['AUT','KAN','SMB']),taskId:z.string().max(100),checkedAt:z.string().datetime(),summary:z.string().max(3000),sourceUpdatedAt:z.string().max(60).nullable()})).max(3).optional()}).strict().superRefine((s,c)=>{if(new Set(s.issues.map(i=>i.key)).size!==s.issues.length||new Set(s.projects.map(p=>p.key)).size!==3)c.addIssue({code:'custom',message:'Duplicate keys'});if(s.issues.some(i=>!i.key.startsWith(i.project+'-')))c.addIssue({code:'custom',message:'Project mismatch'});if(Math.abs(Date.now()-Date.parse(s.fetchedAt))>86400000)c.addIssue({code:'custom',message:'Use a fresh retrieval timestamp'});});
