"use client";
import {useEffect,useState,type FormEvent} from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { ShieldCheck,ArrowLeft,LockKeyhole,Workflow,Database,Brain } from "lucide-react";
const empty={jiraSite:"https://shru2128.atlassian.net",jiraEmail:"",jiraToken:"",mem0Key:"",pineconeKey:"",pineconeHost:"",memoryConsent:false};
export default function Integrations(){
 const [form,setForm]=useState(empty),[saved,setSaved]=useState<any>({}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[ready,setReady]=useState(false);
 useEffect(()=>{fetch("/api/settings",{cache:"no-store"}).then(async r=>{const d:any=await r.json();if(!r.ok)throw new Error(d.error);setSaved(d);setForm(f=>({...f,jiraEmail:d.jiraEmail,pineconeHost:d.pineconeHost,memoryConsent:d.memoryConsent}));setReady(true);}).catch(e=>setMessage(e.message));},[]);
 async function action(path:string,body:any){setBusy(true);setMessage("");try{const r=await fetch("/api/"+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw new Error(d.error);if(path==="settings"||path==="disconnect"){setSaved(d);setForm(f=>({...f,jiraToken:"",mem0Key:"",pineconeKey:""}));}setMessage(d.message??(path==="disconnect"?"Saved key removed. Historical reports are retained.":"Saved securely. Secret inputs have been cleared."));}catch(e){setMessage(e instanceof Error?e.message:"Unable to save.");}finally{setBusy(false);}}
 const field=(name:keyof typeof empty,label:string,secret=false,placeholder="")=><label className="field">{label}<Input type={secret?"password":"text"} autoComplete={secret?"new-password":"off"} spellCheck={false} value={String(form[name])} placeholder={placeholder} onChange={e=>setForm({...form,[name]:e.target.value})}/></label>;
 const disconnect=(provider:string,configured:boolean)=>configured?<Button type="button" variant="ghost" disabled={busy} onClick={()=>{if(window.confirm("Remove this saved key? This does not revoke it at the provider or delete historical reports."))void action("disconnect",{provider});}}>Remove saved key</Button>:null;
 return <><header><a className="brand" href="/"><ArrowLeft size={20}/> Delivery Feedback</a><span className="quiet-link"><ShieldCheck size={18}/> Private workspace</span></header><main className="settings-main"><p className="eyebrow">CONNECTIONS / KEY VAULT</p><h1>Connect with confidence.</h1><p className="muted">Keys are encrypted at rest, used only on the server, and never returned after saving.</p>
 <section className="security-note"><LockKeyhole size={22}/><div><strong>Your keys are not browser storage.</strong><p>Only connection state is shown. Blank key fields preserve saved keys. HTTPS and authenticated access protect the hosted page; use limited-scope provider credentials.</p></div></section>
 <form onSubmit={(e:FormEvent)=>{e.preventDefault();void action("settings",form);}}>
 <section className="panel integration"><div className="row"><h2>01 / Jira</h2><span className="badge">{saved.jiraConfigured?"Key saved · not a health check":"Not connected"}</span></div><p className="muted">Read-only project and issue retrieval. The application never changes Jira issues.</p><label className="field">Jira site<Input value={form.jiraSite} readOnly/></label>{field("jiraEmail","Atlassian account email",false,"you@company.com")}{field("jiraToken","Jira API token",true,saved.jiraConfigured?"Saved — enter a replacement":"Enter a Jira API token")}<div className="actions"><Button type="button" variant="outline" disabled={!saved.jiraConfigured||busy} onClick={()=>void action("test",{})}>Test saved Jira connection</Button>{disconnect("jiraToken",saved.jiraConfigured)}</div><p className="footnote">Use a classic Jira Cloud API token for this site’s Basic-auth endpoint. Scoped tokens using the Atlassian gateway are not supported in this version.</p></section>
 <section className="panel integration"><div className="row"><h2><Workflow size={22}/> 02 / LangChain</h2><span className="badge">Enabled</span></div><p>Runs the retrieval and reporting pipeline. LangChain itself needs no API key. This version uses deterministic Jira checks, not an LLM that could invent status claims.</p><p className="footnote">LangSmith tracing is not enabled. No keys or Jira content are sent to a tracing service.</p></section>
 <div className="integration-grid"><section className="panel integration"><div className="row"><h2><Brain size={21}/> Mem0</h2><span className="badge">{saved.mem0Configured?"Key saved":"Optional"}</span></div><p className="muted">Retain dated risk summaries for future context.</p>{field("mem0Key","Mem0 API key",true,saved.mem0Configured?"Saved — enter a replacement":"Enter Mem0 API key")}{disconnect("mem0Key",saved.mem0Configured)}</section>
 <section className="panel integration"><div className="row"><h2><Database size={21}/> Pinecone</h2><span className="badge">{saved.pineconeConfigured?"Key saved":"Optional"}</span></div><p className="muted">Index and retrieve historical report evidence.</p>{field("pineconeKey","Pinecone API key",true,saved.pineconeConfigured?"Saved — enter a replacement":"Enter Pinecone API key")}{field("pineconeHost","Index hostname",false,"index-id.svc.region.pinecone.io")}<p className="footnote">Requires an existing integrated-embedding index with its text field mapped to <code>chunk_text</code>. A private per-user namespace is generated automatically.</p>{disconnect("pineconeKey",saved.pineconeConfigured)}</section></div>
 <section className="panel"><label className="consent"><Checkbox checked={form.memoryConsent} onCheckedChange={v=>setForm({...form,memoryConsent:v===true})}/><span><strong>Allow report summaries to be sent to Mem0 and Pinecone</strong><br/>Only dated project counts, issue keys, statuses and risk reasons are sent—no API keys, assignee names or full issue descriptions. These services may charge usage fees. Turning this off stops future sends; it does not erase existing provider records.</span></label></section>
 <div className="savebar"><Button type="submit" disabled={!ready||busy}>{busy?"Working…":"Save integrations securely"}</Button><a href="/" className="quiet-link">Back to dashboard →</a></div>
 </form><p role="status" className="notice">{message}</p><section className="panel"><h3>Scheduled reporting</h3><p>Set the delivery-manager cadence and agent names in the dashboard Preferences tab. Scheduled updates preserve dated source snapshots. “Refresh Jira” uses the keys saved here and also updates enabled Mem0/Pinecone integrations.</p></section></main></>;
}
